### ISSUE TITLE
After including Homie.h min() function has to be called as std::min()

### ISSUE THREAD

**Issue by furyfire** [marvinroger/homie-esp8266#22]
After including Homie.h any code that uses the min() function will fail to compile unless you give it a namespace. This is unlike other Arduino libs and causes confusion.

#include <Arduino.h>
#include <Homie.h>
void setup() {
        std::min(2,3);
}

void loop() {
}

**Comment by marvinroger** [comment]
It's not Homie' fault.

The min() you're using when you call the `min()` function is not the `std` one, but the one defined by a #define [there](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Arduino.h#L253). The problem is [ESP8266WiFi.h undefined both min and max](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp#L46). You can try:

```c++
#include <ESP8266WiFi.h>

void setup() {
  min(2,3);
}

void loop() {
  delay(100);
}
```

It won't work either. The issue is tracked at esp8266/Arduino#398

As a workaround, you can [use _min and _max](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Arduino.h#L257).
