### ISSUE TITLE
Homie - can't connect to WiFi network

### ISSUE THREAD

**Issue by averri** [marvinroger/homie-esp8266#233]
I'm testing the HookToEvents example: https://github.com/marvinroger/homie-esp8266/blob/master/examples/HookToEvents/HookToEvents.ino

Trying to connect to the WiFi network using Windows 10, it says "Can't connect to this network".

**Comment by marvinroger** [comment]
I am afraid I cannot do anything here. [The AP is spawned using the esp8266/Arduino API](https://github.com/marvinroger/homie-esp8266/blob/develop/src/Homie/Boot/BootConfig.cpp#L37-L38). Maybe your ESP8266 has some radio problems, but I personally never encountered this issue.

Maybe your Windows 10 complains because there' no Internet access on the ESP8266 AP?

**Comment by averri** [comment]
I connected for the first time in Windows 10, but it does not connect anymore on Windows 10. It just happens on Windows 10, I can connect from Windows 7 to the same device.

Thanks.

**Comment by averri** [comment]
I have discovered how to solve this. Go to **Manage WiFi settings** on Windows 10, and select **Forget Network**. After that, it is possible to connect to the network again.

![image](https://cloud.githubusercontent.com/assets/1898447/20500406/34aba258-b02d-11e6-8ed3-e2d4257cc16a.png)

**Comment by marvinroger** [comment]
Thanks for the information. 👍
