### ISSUE TITLE
Any chance of a setBaseTopic fn?

### ISSUE THREAD

**Issue by stufisher** [marvinroger/homie-esp8266#241]
I cant see this documented in the API, but it would be cool to be able to set the base topic from within the firmware.

I have a mix of devices from various points in v2.0 development, and my base topic is still the old devices, updating the firmware then requires me to send a config update. Plus homie-control is not quite ready for a dynamic basetopic yet, need to make a few changes!

**Comment by marvinroger** [comment]
That's why Homie v2.0.0 is not yet released/marked as stable, because you cannot really rely on it being "frozen".

The problem is we want to keep firmwares "environments agnostic", which is the whole point of the `config.json`. Making the base topic configurable from the firmware would break this rule.

What's wrong with sending a config update?

**Comment by stufisher** [comment]
No worries, i can work round :)

**Comment by marvinroger** [comment]
Thanks :)
