### ISSUE TITLE
Add config for MQTT port

### ISSUE THREAD

**Issue by enavarro222** [marvinroger/homie-esp8266#3]
To use it with a std MQTT broker it could be nice to make MQTT broker port configurable.

It's straightforward to add such option, however in a "pure" Homie framework it's just an other useless option... 

What do you think to add an `homie_port` option that take the value from the `HOMIE_PORT` constant if not given in the config JSON ?

I can propose a PR in this sense.

**Comment by marvinroger** [comment]
I think this is a good idea, but the fact is an Homie server is actually 2 servers: the MQTT broker on 35589 and the OTA HTTP server on port 35590, that respond on the `/ota` path. So maybe you could also add an `homie_ota_port` and an `homie_ota_path`, so that a developer could implement the OTA server on its own HTTP server?

What do you think about it? If you have another ideas, even breaking ones, go ahead! Homie is still young and, well, not used by a lot of people so there will probably be a lot of breaking changes before reaching 1.0.0. ;)

**Comment by enavarro222** [comment]
Nice. I'll do that.
It's just a small change.

A "breaking" idea could be to have a more flexible option system. With the current options by default + other that a dev can declare in his setup for a particular device. But it might be a wrong way as such option can be given by MQTT...

**Comment by marvinroger** [comment]
What do you mean by options?
Le 17 janv. 2016 12:11 AM, "Emmanuel N." <notifications@github.com> a
écrit :
