### ISSUE TITLE
Additional "device_id" field in config.json

### ISSUE THREAD

**Issue by hoalex** [marvinroger/homie-esp8266#45]
Hi there,

I think it would be great if Homie could optionally publish its MQTT messages under ```devices/name``` instead of ```devices/device id```. That way, multiple ESP8266s would be easier to distinguish, as one could simply name them -- for example -- "kitchen", "living room" and so on in configuration mode and then access them by that name via MQTT.
I guess that the current approach was chosen mainly to avoid naming conflicts, therefore I suggest using an optional statement in the ```setup()``` block à la:
```
Homie.useNameForPublish(true);
```

What do you think? :-)

**Comment by jpmens** [comment]
`name` can contain a descriptive text such as `Light relay in living room`, which is great because it allows, say, a Web interface to display this clearly. As an avid hater of white space in topic names (and file system path names) I think this would lead to some confusion. (Of course people could suppress white space in name if they don't want it (`light-relay-in-living-room`).

I tend to think this calls for an additional setting (`sub_topic` ?) which ought to be in the configuration, as we did for `base_topic` in #44.

My 0.01c :smile:

**Comment by marvinroger** [comment]
@jpmens This is what I wanted to do, an additional `device_id` field in the JSON configuration file. It would adhere to the following rules, as stated in [the convention](https://github.com/marvinroger/homie):

> Each device must have a unique device ID. This ID MAY be composed of lowercase letters from a to z, numbers from 0 to 9, and it MAY contain -, but MUST NOT start or end with a -.

@hoalex an `Homie.useNameForPublish(true);` method would not fit as Homie sketches are meant to be portable.

Does it sound good to both of you?

**Comment by jpmens** [comment]
:+1:

**Comment by hoalex** [comment]
Sounds perfect :+1: Thanks for looking into it!

**Comment by marvinroger** [comment]
This will land in 1.3.0! The new `device_id` field is at the top at the root of the JSON config.

**Comment by marvinroger** [comment]
Released!
