### ISSUE TITLE
mqtt.auth is not a boolean error when configuring with mqtt authentication ticked

### ISSUE THREAD

**Issue by rossdargan** [marvinroger/homie-esp8266#60]
I'm getting the error "mqtt.auth is not a boolean" via serial when I send the config with "Use MQTT authentication" ticked (and my credentials entered).

**Comment by rossdargan** [comment]
By the way same error using Chrome and Firefox on Android.

**Comment by marvinroger** [comment]
Again, [check your dependencies](https://github.com/marvinroger/homie-esp8266/blob/master/docs/2.-Getting-started.md#1a-for-the-arduino-ide). ArduinoJson >= 5.0.8. There is a bug [I submitted to the ArduinoJson issue tracker](https://github.com/bblanchon/ArduinoJson/issues/214), that is fixed in 5.0.8.

**Comment by rossdargan** [comment]
:( I'm really sorry - I did install all these libraries through the ide. I have no idea why they are all out of date. Is that usual?

**Comment by marvinroger** [comment]
I have no idea, everything is up-to-date on my library manager!

**Comment by marvinroger** [comment]
But yes as @jpmens said, maybe update your Arduino to 1.6.8?

**Comment by rossdargan** [comment]
You are of course correct, sorry! 1.6.8 did allow me to update
